"""empty message

Revision ID: 058f16663f06
Revises: 
Create Date: 2025-11-14 16:32:08.785370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058f16663f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speciality', sa.String(), nullable=False))
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('speciality')

    # ### end Alembic commands ###
